version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.4
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node